nagios_cfg_target: "prod"
nagios_cfg_org: "nerc"
nagios_cfg_instance: "{{ nagios_cfg_org }}-nagios"
nagios_cfg_prefix: "/srv/{{ nagios_cfg_instance }}"
nagios_cfg_etc: "{{ nagios_cfg_prefix }}/etc-nagios"
nagios_cfg_hosts: []
nagios_cfg_services: []
nagios_cfg_template_files:
  - "templates.cfg"
  - "commands.cfg"
  - "hosts.cfg"
  - "services.cfg"
  - "servicegroups.cfg"
  - "hostgroups.cfg"
